build:
	pdflatex *.tex
	pdflatex *.tex

clean:
	rm */*.pdf */*.aux */*.dvi */*.log */*.toc */*.html */*.4ct */*.4tc */*.css */*.idv */*.lg */*.tmp */*.xref *.pdf *.aux *.dvi *.log *.toc *.html *.4ct *.4tc *.css *.idv *.lg *.tmp *.xref


